### ISSUE TITLE
Gulp async task completion

### ISSUE THREAD

**Issue by ritikbhardwaj** [mrgigabyte/hapi-boilerplate#2]
Tasks in gulp need to be stopped either by returning streams or consuming promises or by callbacks (Async completion). When I quit gulp, some tasks do not complete successfully.

![Screen Shot 2020-01-03 at 5 24 54 PM](https://user-images.githubusercontent.com/51000843/71722284-5238c380-2e4e-11ea-8cf4-fbea609d9c51.png)

**Comment by mrgigabyte** [comment]
I'm aware about the issue, I haven't resolved it yet. Thanks! 
Let me know if there any more bugs
